name: Compile LaTeX

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      run: docker build . --file .devcontainer/Dockerfile --tag latex-compiler

    - name: Compile LaTeX
      run: |
        docker run --rm \
          --volume ${{ github.workspace }}:/latex \
          latex-compiler /bin/bash -c \
          "cd /latex && make clean && make"

    - name: Archive PDF artifact
      uses: actions/upload-artifact@v2
      with:
        name: output-pdf
        path: ./build/main.pdf
      env:
        node-version: '20'